### ISSUE TITLE
Blank line in placeholder function

### ISSUE THREAD

**Issue by merlinosayimwen** [aetherpowered/aron-ts#1]
Hello, 
I wanted to report something that has been bothering me for some time now.
The empty `placeholder` function does have a blank line in its body.

https://github.com/aetherpowered/aron-ts/blob/81dbe5010f2b4323648e6f3270ff2cf8fa8a74fc/index.ts#L2

```ts
function placeholder() {

}
```

Could you please remove this and make it to something like this:

```ts
function placeholder() { }
```

Cheers,
Merlin Osayimwen

**Comment by merlinosayimwen** [comment]
I fixed it. Sorry for the long delay

**Comment by pascalklassen** [comment]
shizophrenic disorder?

**Comment by merlinosayimwen** [comment]
@pascalklassen we were testing something. Don't be rude.
